collections:
  film:
    output: true
  music:
    output: true
  film-tags:
    output: true
    permalink: /film-tags/:name/
  music-tags:
    output: true
    permalink: /music-tags/:name/
  type:
    output: true
  post:
    output: true

defaults:
  - scope:
      path: ""
      type: "film"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag