collections:
  film:
    output: true
  music:
    output: true
  film-tags:
    output: true
    permalink: /film-tags/:name/
  music-tags:
    output: true
    permalink: /music-tags/:name/
  type:
    output: true

# SEO/OpenGraph
logo: /assets/images/Universe.png

description: Master description test.

author:
  twitter: Jay Friesen

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/Universe.png
      author: Jay Friesen
# /SEO

defaults:
  - scope:
      path: ""
      type: "film"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag